# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
            options={
                'verbose_name': '书籍管理后台',
                'db_table': 'book',
            },
        ),
    ]
